micronaut:
  application:
    name: kasaDoKodigo

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    platform: postgres
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/kasadokodigo?createDatabaseIfNotExist=true`}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true